[tool.poetry]
name = "vrc2t"
version = "0.1.0"
description = ""
authors = ["phillychi3 <phillychi3@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
python-osc = "^1.9.3"
numpy = "^2.2.4"
setuptools = "78.1.0"
faster-whisper = "1.2.1"
ctranslate2 = "4.6.0"
onnxruntime = "1.22.0"
av = "16.1.0"
transformers = "4.51.3"
pyaudiowpatch = "^0.2.12.8"
sentencepiece = "0.2.1"
pydub = "0.25.1"
audioop-lts = {version = "0.2.2", markers = "python_version >= \"3.13\""}

[tool.poetry.group.dev.dependencies]
pyinstaller = {version = "^6.22.2", python = ">=3.12,<3.16"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = [".venv", ".git", "__pycache__", "build", "dist"]
line-length = 90


[tool.ruff.lint]
select = ["E", "F"]
fixable = ["A", "B", "C", "D", "E", "F" ]
