/* eslint-disable @typescript-eslint/no-require-imports -- CommonJS CLI entry point. */
const { createRequire } = require('node:module')
const { spawn } = require('node:child_process')
const crypto = require('node:crypto')
const fs = require('node:fs/promises')
const path = require('node:path')

// Resolve the tool shipped with our installed electron-builder under pnpm.
const builderRequire = createRequire(require.resolve('electron-builder'))
const { getPath7za } = builderRequire('app-builder-lib/out/toolsets/7zip')

const { version } = require('../package.json')

// The installer checks for each asset's entry file to confirm it really
// unpacked; the backend one is overridable so the regression can use a stand-in.
const BACKEND_ENTRY = process.env.VRC_BACKEND_ENTRY || 'vrc-v2t-backend.exe'

// Everything the web installer downloads besides electron-builder's own app
// package. The emotion model is optional at install time, so it is packed the
// same way as the backends rather than shipped inside the app package.
const ASSETS = [
	{
		id: 'cpu',
		define: 'CPU',
		source: 'build/python-cpu/vrc-v2t-backend',
		name: `vrc2t-backend-cpu-${version}-x64.7z`,
		entry: BACKEND_ENTRY
	},
	{
		id: 'cu126',
		define: 'CU126',
		source: 'build/python-cu126/vrc-v2t-backend',
		name: `vrc2t-backend-cu126-${version}-x64.7z`,
		entry: BACKEND_ENTRY
	},
	{
		id: 'emotion',
		define: 'EMOTION',
		// Same override scripts/prepare-emotion.ps1 and backend/runtime.py honour.
		source: process.env.VRC_EMOTION_MODEL_DIR || 'build/models/emotion',
		name: `vrc2t-emotion-${version}.7z`,
		entry: 'model.onnx'
	}
]
// Release assets live under the tag the release workflow publishes.
const BASE_URL =
	process.env.VRC_ASSET_BASE_URL ||
	`https://github.com/phillychi3/vrc-v2t-osc/releases/download/v${version}`
// Headroom for the archive copy plus NSIS temporaries next to the unpacked tree.
const SPARE_MEGABYTES = 256

function nsisString(value) {
	// NSIS expands $ inside double-quoted strings; $$ is a literal dollar sign.
	return String(value).replace(/\$/g, '$$$$')
}

async function directorySize(root) {
	let total = 0
	for (const entry of await fs.readdir(root, { withFileTypes: true, recursive: true })) {
		if (entry.isFile()) {
			total += (await fs.stat(path.join(entry.parentPath, entry.name))).size
		}
	}
	return total
}

async function hashFile(file, algorithm) {
	const hash = crypto.createHash(algorithm)
	hash.update(await fs.readFile(file))
	return hash.digest('hex').toUpperCase()
}

function run(command, args, cwd) {
	return new Promise((resolve, reject) => {
		const child = spawn(command, args, { cwd, stdio: 'inherit', windowsHide: true })
		child.on('error', reject)
		child.on('close', (code) =>
			code === 0 ? resolve() : reject(new Error(`${path.basename(command)} failed: ${code}`))
		)
	})
}

async function packAsset(sevenZip, source, archive) {
	// 7-Zip otherwise updates an existing archive and can retain deleted files.
	await fs.rm(archive, { force: true })
	console.log(`Compressing ${path.basename(archive)}`)
	await run(
		sevenZip,
		[
			'a',
			'-t7z',
			'-mx=5',
			'-m0=LZMA2',
			'-md=32m',
			'-mmt=2',
			'-mtc=off',
			'-mta=off',
			'-mtm=off',
			archive,
			'.'
		],
		source
	)
}

async function prepareAssets(projectRoot) {
	const output = path.join(projectRoot, 'build/installer-payload')
	await fs.mkdir(output, { recursive: true })
	const sevenZip = await getPath7za()
	await fs.copyFile(sevenZip, path.join(output, '7za.exe'))
	const toolRoot = path.dirname(path.dirname(sevenZip))
	for (const name of ['LICENSE.txt', 'COPYING']) {
		await fs.copyFile(path.join(toolRoot, name), path.join(output, name))
	}

	const built = []
	for (const asset of ASSETS) {
		const source = path.join(projectRoot, asset.source)
		// Fail loudly: a stale archive would be published against the new version.
		await fs.access(source)
		const archive = path.join(output, asset.name)
		await packAsset(sevenZip, source, archive)
		const bytes = (await fs.stat(archive)).size
		const unpackedBytes = await directorySize(source)
		built.push({
			id: asset.id,
			define: asset.define,
			name: asset.name,
			entry: asset.entry,
			bytes,
			unpackedBytes,
			requiredMegabytes: Math.ceil((bytes + unpackedBytes) / 1024 / 1024) + SPARE_MEGABYTES,
			downloadMegabytes: Math.round(bytes / 1000 / 1000),
			sha512: await hashFile(archive, 'sha512'),
			sha256: await hashFile(archive, 'sha256')
		})
		console.log(`${asset.name}: ${bytes} bytes, unpacked ${unpackedBytes} bytes`)
	}

	const lines = [
		'; Generated by scripts/prepare-assets.cjs. Do not edit.',
		`!define ASSET_BASE_URL "${nsisString(BASE_URL)}"`
	]
	for (const asset of built) {
		lines.push(
			`!define ASSET_${asset.define}_NAME "${nsisString(asset.name)}"`,
			`!define ASSET_${asset.define}_ENTRY "${nsisString(asset.entry)}"`,
			`!define ASSET_${asset.define}_HASH "${asset.sha512}"`,
			`!define ASSET_${asset.define}_REQUIRED_MB "${asset.requiredMegabytes}"`,
			`!define ASSET_${asset.define}_DOWNLOAD_MB "${asset.downloadMegabytes}"`
		)
	}
	await fs.writeFile(path.join(output, 'installer-assets.nsh'), `${lines.join('\n')}\n`)
	await fs.writeFile(
		path.join(output, 'installer-assets.json'),
		`${JSON.stringify({ version, baseUrl: BASE_URL, assets: built }, null, '\t')}\n`
	)
}

module.exports = { prepareAssets }

if (require.main === module) {
	prepareAssets(path.resolve(process.argv[2] || path.join(__dirname, '..'))).catch((error) => {
		console.error(error)
		process.exitCode = 1
	})
}
